### ISSUE TITLE
Right Context going out of the viewport

### ISSUE THREAD

**Issue by riya332** [isaacplmann/angular2-contextmenu#34] opened 2016-12-29 07:30 UTC
Hi @isaacplmann , 
Can you handle this case of positioning of right context menu If it crosses out the browser's view-port i.e. when it goes out of window , allign it to left side or so.

Thanks,
Riya

**Comment by isaacplmann** [comment] 2017-01-05 20:41
This should be fixed in 0.7.0

**Comment by isaacplmann** [comment] 2017-01-06 13:51
Closing. Reopen if it isn't fixed.

**Comment by riya332** [comment] 2017-01-16 06:26
Hi @isaacplmann , It's not working if the menu opens at the bottom of the page. Can you reposition it above the div if it breaches out of view port from bottom.

**Comment by riya332** [comment] 2017-01-20 09:38
Hey @isaacplmann , I have tested it for above browsers as well and it's not working. By the way , The case is right click menu should be at the bottom of the page .At the very bottom , If you try to open it , goes below the screen and it's not visible .
Please look into the same

**Comment by riya332** [comment] 2017-01-20 09:39
I'm using 0.7.1 , tried with 0.7.0 as well

**Comment by isaacplmann** [comment] 2017-01-23 16:27
I still can't reproduce this.  Any ideas about why your environment might be different from mine?

**Comment by isaacplmann** [comment] 2017-01-30 15:37
Is it the `body` that is scrolling or some element with `overflow:auto`?

**Comment by riya332** [comment] 2017-02-09 12:25
Hello @isaacplmann,

Here's the exact case.

I have an unordered list which has gone beyond the browser's viewport at the bottom. When I try to open the menu of the last visible list item which is close to viewport (on right click), 90% of the menu is below the viewport. I could scroll the page but then it will close the right context.
![actual](https://cloud.githubusercontent.com/assets/7879363/22783167/a36b0952-eef0-11e6-95dd-bc6a632339dd.jpg)


 

Could you please reposition (may be top placement) the menu if it is related to those which are closer to the viewport ? 

The menu should be visible at the bottom of the list item only when there is enough space for menu accommodation below the respective list item. Otherwise, it should be placed at top of the list item .Something as this 
![desired](https://cloud.githubusercontent.com/assets/7879363/22783196/b63f3a26-eef0-11e6-8a6b-3ec19113c491.jpg)

**Comment by isaacplmann** [comment] 2017-02-10 14:21
Thank you for the pictures, but in all my tests, the correct behavior is happening.

I noticed @lagofvc reacted to a few of the comments on this issue.  Are you experiencing the same issue?

**Comment by isaacplmann** [comment] 2017-02-10 14:23
How are the ancestors of the `<context-menu>` element styled?  Maybe that has something to do with it.  Could you send me a github repo that reproduces this issue?  I'm kind of at a loss.

**Comment by lagofvc** [comment] 2017-02-10 18:24
FYI, it got fixed for us when we updated to `angular2-contextmenu@0.7.5`.   Our context-menu now drops-up when at the bottom.

**Comment by isaacplmann** [comment] 2017-04-03 13:07
Closing.  Please open an issue at [ngx-contextmenu](https://github.com/isaacplmann/ngx-contextmenu) if this still doesn't work.

**Closed by isaacplmann** 2017-04-03 13:07 UTC
