### ISSUE TITLE
Context menu position issues within CSS transform

### ISSUE THREAD

**Issue by jredd** [isaacplmann/angular2-contextmenu#42] opened 2017-01-19 20:39 UTC
I have a component that I insert into different views and use the context menu in that component. It works great when it's in the main view on any of my pages but when I add the component to a modal window the placement of the menu is pretty far off and in some cases the menu goes below the fold of the page and the user can't even see all of the menu items. I'm not even sure where to begin on this...

**Comment by isaacplmann** [comment] 2017-01-19 20:45
I think that's being caused by the way I'm using css to position the context menu.  The context menu is set to `position: absolute` and then the `top` and `left` properties are set relative to the window.  This works fine as long as there isn't another parent element of the context menu that has `position: relative`.  When that happens the `top` and `left` properties offset the context menu based on the top left corner of that element, instead of the window.

There are a couple workarounds, but no great solution yet:
1. Don't style any parent elements of the context-menu element with `position:relative`.
2. Add `margin-top` and `margin-left` properties to the `.angular2-contextmenu` class that are the exact opposite value of the top/left corner of the element that has `position:relative`.

I'll think about a better way to do this.  Probably having javascript calculate the values would work.

**Comment by isaacplmann** [comment] 2017-01-19 20:47
Oh, another workaround is to have one global context menu in a template at the root of your app and then use the contextMenuService to trigger it [like this](https://github.com/isaacplmann/angular2-contextmenu#context-menu-in-a-different-component).

**Comment by jredd** [comment] 2017-01-19 20:50
As of right now I don't control the css of the modal window at all. I use ng2-boostrap for my frontend stuff. I'd prefer not to do a global menu if I can help it but I'll def take a look at your third suggestion. 

https://valor-software.com/ng2-bootstrap/#/

**Comment by isaacplmann** [comment] 2017-01-19 21:00
It looks like `.modal-dialog` is the culprit.

```css
.angular2-contextmenu {
  margin-top: -30px;
}
```

That should take care of the vertical positioning, but it's hard to offset `margin: auto` for the horizontal position.  You'll probably need to use javascript to calculate the left edge of the `.modal-dialog` element.  Or you could submit a PR for me... 😀

**Comment by jredd** [comment] 2017-01-19 23:12
One way I could think of would be being able to declare it's container and then setting it's positioning based off that container?

**Comment by isaacplmann** [comment] 2017-01-20 03:13
I like that solution. I'd want it to default to the plain css solution
since that is more performant and works for most users. I won't be able to
implement it for a while but would be happy to review a pr.

**Comment by isaacplmann** [comment] 2017-01-23 16:25
I just came across this same scenario in my app, so fixing this bug has been moved up my priority list.

**Comment by isaacplmann** [comment] 2017-01-27 19:36
This should be fixed in 0.7.3.

It's actually not `position: relative` but `transform` that causes the issues.  A lot of frameworks use `transform: translate3d(0px 0px 0px)` to force the browser to use the GPU.  When the `<context-menu>` element is inside one of those elements, the `top` and `left` properties are calculated based on the transformed element instead of the body.

**Comment by kotrao** [comment] 2017-01-31 04:05
I have a positioning issue with the context menu. It is displaying in such a way that its top half is getting underneath the browsers addressbar and it is not visible. Looks like its top-margin calculation is going wrong. Any suggestions as to how I can go about addressing it?

**Comment by isaacplmann** [comment] 2017-01-31 14:13
@kotrao what are the css properties on the parents of the `<context-menu>` element?  Specifically, do any of the parent elements have a `transform` property?  Or `position: relative`?

Also, is the context menu tall enough that it would go off the bottom of the viewport if positioned normally?

**Comment by kotrao** [comment] 2017-02-01 01:59
Please see below for the hierarchy of parents. Also I have only 4 lines in my context menu. Right now, context menu  is using mouse click position as bottom right. As a result it is being cut off by browser address bar.

<div style="position:absolute;top:35px;height:100%;width:100%;display:table; border-collapse: collapse;border:none;outline:none"> 
          <div style="display: table-cell;width:200px;vertical-align: top" >
                <div style="height:100%">
                       <div> ....something else...</div>
                       <div style="position:absolute;top:200px;left:-200px">
                               **<context-menu #folderContextMenu> 
                                        ....4 items in the menu..
                               </context-menu>**
                        </div>
                 </div>
           </div>
</div>

**Comment by isaacplmann** [comment] 2017-02-01 14:00
Thanks for the html - that let me reproduce it.  See if version 0.7.5 fixes the problem.

**Comment by jredd** [comment] 2017-02-08 20:20
You definitely fixed the issue when the context menu is inside of modals... The issue is, with the update, it's broken the modal in the regular view...

**Comment by isaacplmann** [comment] 2017-02-08 20:24
Ok, send me the html structure like @kotrao did.  I'll try to reproduce your issue.

**Comment by isaacplmann** [comment] 2017-02-10 17:26
I may have fixed your issue with version 0.7.7.  I wasn't getting the styles from any stylesheets when I calculated the position of the context menu.

**Comment by jredd** [comment] 2017-02-10 18:08
Nope wasn't fixed on my side. The menu that I have the context menu on is around 5 components deep in my dom. I'm using angular2 . It works fine in version 0.5.3...

**Comment by JimSangwine** [comment] 2017-03-23 06:14
Hi Isaac. Thanks for the great component.

This issue is affecting me too. 
Because .col-* classes in Bootstrap have position: relative I had to add this override:

`.col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3, .col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, .col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, .col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, .col-lg-12 {
    position: inherit;
}`

Everything seems to be OK for now, but presumably at some point I'll probably hit the use-case the authors were guarding against.

I'd be OK with the idea of having a single global context-menu as long as it were possible to define the contextMenuItem templates in the components that would trigger it. Having a collection of context menus at the root of the application always loaded and waiting to be triggered does not appeal though.

**Comment by isaacplmann** [comment] 2017-03-24 14:08
Yeah, that's a hacky workaround - sorry about that.  I have an idea for a solution that will dynamically add context menus to the root as needed - which will avoid all these annoying css conflicts.  I'll update all the related issues once it's ready - maybe a week from now.

**Comment by JimSangwine** [comment] 2017-03-25 01:27
Awesome, thanks Isaac!

**Comment by isaacplmann** [comment] 2017-04-03 13:05
Should be fixed by the move to [ngx-contextmenu](https://github.com/isaacplmann/ngx-contextmenu).  Please open an issue there if this doesn't work.

**Closed by isaacplmann** 2017-04-03 13:05 UTC

**Comment by JimSangwine** [comment] 2017-04-06 09:03
Confirmed and my ugly hack removed. Thank you so much!
